---
abstract: 'GD::Barcode::QRcode View Class'
author:
  - 'Hideo Kimura C<< <<hide@hide-k.net>> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.84'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-GD-Barcode-QRcode
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.6
  Filter::Util::Call: 0
  GD::Barcode::QRcode: 0.01
  MRO::Compat: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
