# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-View-GD-Barcode-QRcode
version:      0.03
version_from: lib/Catalyst/View/GD/Barcode/QRcode.pm
installdirs:  site
requires:
    Catalyst:                      5.5
    GD::Barcode::QRcode:           0.01
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
